name: Build and Deploy
on:
  push:
    branches: master
jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1
      
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - name: Install Project Dependencies
        run: yarn install
      
      - name: Install Gatsby CLI
        run: yarn global add gatsby-cli@2.12.34
      
      - name: Build
        run: yarn build
      
      - name: Verify build
        run: ls -la public

      - name: List output files
        run: find public/ -print
      
      # - name: Setup SSH
      #   run: |
      #     mkdir -p ~/.ssh/
      #     echo "${{ secrets.ssh_private_key }}" > ~/.ssh/deploy_key
      #     sudo chmod 600 ~/.ssh/deploy_key
      #     ssh-keyscan -H "${{ secrets.host }}" > ~/.ssh/known_hosts
      
      # - name: SFTP upload
      #   run: sftp -i ~/.ssh/deploy_key ${{ secrets.deploy_user }}@${{ secrets.host }} <<< $'cd ${{ secrets.destination_path }} \n put -r public/*'